### ISSUE TITLE
Possible error in Count_Distance function

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#1]
```
      type Value_Type is digits 2 range 0.0 .. 9999999.0;
```

Two digits of relative accuracy is very low.

It means there is no difference between the number 999 and 990.

Was this your intention?

**Comment by thindil** [comment]
Ok, maybe I don't understand too good Ada specification ;) But _relative accuracy_ (for float point types) means _minimum accuracy_ so there should be no problem.
http://www.ada-auth.org/standards/rm12_w_tc1/html/RM-3-5-7.html

Anyway, I was done few test now and looks like everything works as long as values are in range. Maybe I'm doing something wrong?

**Comment by alkhimey** [comment]
Yes, that is how I understand it as well. The compiler is guaranteed to provide the specified accuracy, but it can also provide better accuracy, like you have verified in your tests.

**Comment by thindil** [comment]
Ok, I was changed this (and in few other places this same problem) to just ranged Float. It should now not cause confusion anymore :)

Thank you for report. Im closing it, but if someone think that problem is not solved yet, please reopen (or ask for it).
