### ISSUE TITLE
Allow going back one menu level

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#10]
Sometimes it is convenient to go one menu level back instead of exiting to the world map.

For example when searching for an option that I do not know which sub-menu it belongs to.

**Comment by thindil** [comment]
If this is not problem, could you, please write in which exactly places this should be added? I'm sure I was added it in few places just probably I missed few other too :)

**Comment by alkhimey** [comment]
This happens on every menu under the main menu for example: "e -> wait order".

I think I understand the problem now. These menus can be accessed from a shortcut as well (for example "w"), so the program needs to keep track of how the menu was open in order to implement the "go back" functionality.

**Comment by thindil** [comment]
In help, there is option to back to help menu (with 'm' key), here I don't want to change because it mess later keybindings for closing windows.
Wait - probably you mean "Wait X minutes" option? I can change here. Same if i guessing, you mean for example: rename ship, etc?

**Comment by thindil** [comment]
I was done few tests and to be honest, adding option to back to earlier menu just made everything more complicated (more keystrokes). So, at this moment I'm against this, unless someone can tell me exact places where this should be done. If yes, please reopen or just comment this issue with informations.
