### ISSUE TITLE
"F1" button opens terminal window's help instead of game's help

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#11]
Can be reproduced with gnome-terminal on Ubuntu.

Additionally, sometimes the button for help is "H" and sometimes it is "F1". A possible way to fix the issue is to assign "H" to be the button for help in any context.

![screenshot from 2017-11-18 11-44-41](https://user-images.githubusercontent.com/652603/32979018-e46bf68a-cc55-11e7-9979-04967c73e738.png)

**Comment by thindil** [comment]
I think assign in main menu help to F1 will be better solution. Assigning help to H button can make some mess with menu's searching (it will be impossible to select any menu entry which will be contains 'h' letter). And reason for use 'h' in main menu is same as in issue #9 - backward compatibility with old keys settings.

**Comment by thindil** [comment]
Ok, should be now better, default key is F1 for help everywhere, but this can be changed in game options now.
