### ISSUE TITLE
Help section needs improvment

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#12]
Currently it is a blob of text, and it is hard to find answers to question a novice player might have.

Usually, only very dedicated players have the will power to read a help sections completely and understand what is written. I think usually players skim help for specific information.

Some suggestions:

1. Reorganize into a FAQ, or more fine grained sub-categories (What should I do if my crew is hungry? Why can't I move the ship? How do I repair the ship? etc.)

2. Use some coloring scheme. For example color yellow all occurrences of menu items, color blue game items etc.

3. Some "advice engine" that would look into the game state and tell the player what is the next action required to do and how to do it ("ship is damaged, you can repair it by ...")

![screenshot from 2017-11-18 11-33-42](https://user-images.githubusercontent.com/652603/32979070-fe751d3a-cc56-11e7-8648-52b5fe8a884a.png)
![screenshot from 2017-11-18 11-33-49](https://user-images.githubusercontent.com/652603/32979071-feb432b8-cc56-11e7-9003-4451fdb3c9c0.png)

**Comment by alkhimey** [comment]
I can help reorganize it but before that I think that we need to agree about how coloring hints and sub-menu levels will work.

**Comment by thindil** [comment]
Ok, then lets try step by step ;)

1. How about just add section Frequently Asked Question to current help menu? And just group all questions on one page, so user don't need to switch back and forth to find answer/question?
Just adding new section in help is very simple and don't need any code changes - everything is in text file ;) Problem with current help is that it is wrote by someone who very good know game (me), thus probably many basic informations is missed there. So, help is definitely needed here :) You may find more informations about how to edit help in MODDING.md file:
https://github.com/thindil/steamsky/blob/master/bin/doc/MODDING.md

2. How about just add ability to color any text in help? Something like color tag `{blue}some colorized text{/blue}`, etc? Maybe this will be better option?

3. This I'm afraid need some more details ;) How exactly that "advance engine" (or "tutorial engine", if I good guessing) should works?

**Comment by alkhimey** [comment]
1. That would be helpful.
2. Yes, that is what I had in mind, You can also add foreground color to allow more diversity. Additionaly, now I see in the modding section that special variables and keys already have special representation, so why not automatically color them as well.
3. This is something too advanced, so I do not know either. I was imagining something that would look at game state and deduce what is the best action to do (based on status and priorities) and tell the player how to do it. For example, if you started a mission, it will tell you that you need to undock, once you have undocked it will tell you to press "%" or "5". If ship is damaged, it will tell you that you need to repair it and how to do it. If repair kit is missing, it will tell this as well. If you are aobut to go to a mission and the suplies are to low to complete, it will tell you how to buy supplies.

**Comment by thindil** [comment]
1. Okies, so, we need someone who start doing this :)
2. I prefer (for future) keeping this plus colors separated. Later, when I switch whole game to graphical UI, I wish to switch help to HTML or something like this and then colors will be done in other way. So, soon I will start doing this colors.
3. Okies, then I propose to put on hold for now this proposition- lets start "only" with FAQ and colors/bold text plus generally redesigned help. This tutorial will be need a lot work and just double many current in-game messages. Probably at start better can be just add random hints to game main menu.

**Comment by thindil** [comment]
Ok, after trying few options I must said that this is impossible for me to do it (colors). Whole help text is dynamically loaded to game thus setting colors (in ncurses) is almost impossible or require too much work with too small effect. So at this moment I close this issue (here are no chances to implement it before version 2.0 and later will be simply outdated with new interface). If someone can do it, feel free to reopen this issue and apply patch/merge request with code (just before release version 1.9).
