### ISSUE TITLE
Add aggregated information about ship, crew and mission

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#13]
I do not know exactly how it should look, but I feel the need to have some status window or quick access menu that would display more of the critical information (ship speed and game time is already displayed):

1. Time left to complete the mission and it's objective.
2. Number of Charcollum.
3. Ship damage of each part.
4. Each crew member status: order, position, hungry,thirsty, tired etc.

**Comment by alkhimey** [comment]
At the left top corner there are some symbols:

![selection_534](https://user-images.githubusercontent.com/652603/32979177-03c06810-cc59-11e7-8356-7cdde36519c4.png)


I did not figure what they are. Do they display some of the statuses mentioned above?

**Comment by thindil** [comment]
Some critical informations are displayed when needed, like low level of food/fuel/drinks. You can even configure warnings levels in game options (again, it show that help needs a lot of help :) ). Separate info for each ship part and crew member - this will be a lot informations on screen ;) Problem with console is that it have very low amount of space. This is why this informations are "hidden" in ship info and crew info screens. Thus, I'm not sure did in current state of game (as console game) it is possible to do without take literally whole screen.

About this symbols: yes, partially ;) (again, problem with help system I see). It only show most critical informations like no crew members on selected duties (pilot/engineer/gunner/etc).

**Comment by alkhimey** [comment]
Maybe it is possible to add a quick info menu that will open when pressing a button. It will take full screen, but every menu does.

What is the meaning of each symbol?

**Comment by thindil** [comment]
But if you been have more crew and bigger ship later, it simply take whole screen that informations ;) 20 crew members + 40 ship modules may take full console. So, it will simply ends as merged ship+crew info screens :) There is too much important info about each crew member (and I plan to add a lot more info much later) to put everything in one screen, I'm afraid. I think this can be added much later, when I switch from console version to graphic. At this moment it may be almost impossible to add that info without cluttering whole screen.

Symbols: Pilot/Engineer/Gunners/Repairs/Manufacturing/Upgrading ship/Talking in bases(with ships)/Cleaning ship
They are explained (with colors codes) in help ;) So, again, help need help.

**Comment by thindil** [comment]
Ok, I'm closing this issue, for reasons mentioned above - in current state of game (console-based) that info will simply clutter whole screen. Anyway, as usual, thank you for proposition and discussion on it.
