### ISSUE TITLE
Mission time limits makes them hard to complete

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#14]
Most missions require to set ship to full speed (the default at the beginning of the game is quarter speed). Doing a mission in half speed is sometimes impossible as well and always marginal (several hours delay is possible, but not more).

If the player have to fight or want to diverge for some time to explore an area (as novice player might do), or if the pilot becomes tired, this significantly reduces the chances of completing the mission.

I suggest to tie the time given to complete the mission to it's reward, reputation of the player or to the game's time. This way novice players will have plenty of time to complete missions, but the game will become harder as the player make progress.

Example:

![screenshot from 2017-11-18 12-33-05](https://user-images.githubusercontent.com/652603/32979380-de6a2930-cc5c-11e7-983c-5082e709e7ba.png)

At half speed the time required to complete this mission is: `80*(80/60) = 106 hours`. The time that is given is `107 hours`.

**Comment by thindil** [comment]
Main reason why it have so short time sets for finish missions is that missions currently gives lots of money/reputation to selected base (or bases) for finish it. At this moment, especially at beginning it is good to fly with full speed (it gives some advantages but raise fuel usage). I have two propositions which we can discuss to solve this problem:

1. Raise a bit time for complete mission (i mean by max 10%). It should help a bit, especially with this longest missions and still keep reward from missions balanced.
2. Double time for complete mission but reduce (by 25-50%) rewards from missions. Generally missions are very easy to finish, especially with full auto movement and full speed (as I was wrote above).

About depending on reputation or game time: not sure about this solution. In this game you don't need to take bigger ship to continue play. If someone decide to stay with small ship, may have solid problems in longer game play. Same can be with reputation or any other than used ship speed requirements.

**Comment by alkhimey** [comment]
If you are afraid that changing time for completion will break the balance in the game, you can at least make the full speed to be the default speed.

**Comment by thindil** [comment]
It is possible in game options :) So, anyone may set any speed he/she wants. This is why I added this option :) If only default speed is problem, then maybe we don't need to change whole system?

**Comment by thindil** [comment]
Ok, default ship speed changed, we will see if it helps. If not, please reopen this issue. And as usual, thanks for suggestion :)
