### ISSUE TITLE
Green background?

### ISSUE THREAD

**Issue by LJNIC** [thindil/steamsky#15]
Hi, this game looks great. For some reason, my background is a sort of lime green instead of the black in the screenshots?

**Comment by thindil** [comment]
Hello and thanks for appreciation :) Lime green background - it is because you have that default color set for terminal. Maybe I should try set background color for game?

**Comment by LJNIC** [comment]
Ah, it pulled a colour that isn't actually the background. How tied into the terminal is the game?

**Comment by thindil** [comment]
Depends on version: current stable is very tied - it is terminal only version. Development version is rewritten with GUI - it is completely independent from terminal (and should looks on Windows or Linux that same). Ok, I will try to force current stable version to use always black color as background ;)

**Comment by thindil** [comment]
I'm afraid I can't fix this problem, this is limitation of terminal. By default game use black color for background as set by ncurses. But if someone have set different colors for background in graphical terminal (like xterm or gnome-terminal), ncurses can't change it. If someone knows how to workaround this problem, please reopen this issue.
