### ISSUE TITLE
Crash when trying to board a harpooned ship

### ISSUE THREAD

**Issue by ShinQuickMan** [thindil/steamsky#17]
Attempts at boarding when a ship is harpooned (whether one's own or the enemy's) always results in the game crashing. Here's what I got in the error log:

2018-05-16 22:56:13
Version: 2.0.5
Exception: CONSTRAINT_ERROR
Message: combat.adb:775 range check failed
-------------------------------------------------
[**directory**]
0x5a996e
0x5bbbe2
0x662533
0x41955d
0x417255
[/lib/x86_64-linux-gnu/libc.so.6]
0x7fe1d3e8082e
[**directory**]
0x4172b8
0xfffffffffffffffe

**Comment by thindil** [comment]
Hello, thank you for report and I'm sorry for problems. This should be fixed now (I will release new version very soon). Temporary workaround: just equip crew members which going on enemy ship with weapon ;) Crash is caused because crew members don't have equipped any weapon.
