### ISSUE TITLE
Crash when moving after a successful boarding mission

### ISSUE THREAD

**Issue by ShinQuickMan** [thindil/steamsky#18]
More harpoon bugs. After wiping out an enemy crew via boarding mission, any movement in the world map will result in instant crashing. Error log entry:

2018-05-17 17:07:42
Version: 2.0.5
Exception: CONSTRAINT_ERROR
Message: ships-crew.adb:41 range check failed
-------------------------------------------------
[**DIRECTORY**]
0x544d61
0x52dd5c
0x5305f7
0x66d556
0x4197a1
0x417255
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f570d99e82e
[**DIRECTORY**]
0x4172b8
0xfffffffffffffffe

-------------------------------------------------

**Comment by thindil** [comment]
Now we have problem: I can't replicate this bug. I have question: Did this save is this save which was used during previous bug (#17)? If yes, save can be corrupted and this can cause this crash.

**Comment by ShinQuickMan** [comment]
Nope. This was done on a different save. And, of course, I actually went on and equipped my party this time around. To wit, both occurred during/after a destroy target mission. Not sure if that could be part of the problem.

**Comment by thindil** [comment]
Ok, I was checked few things, maybe it will be fixed now (just in new saves, old is unfortunately broken). If problem will be again, please reopen (or create new issue). Thank you again for report.
