### ISSUE TITLE
Skills and Skill Rank Errors

### ISSUE THREAD

**Issue by ShinQuickMan** [thindil/steamsky#21]
Skills ranks seem to either be conveyed erroneously, or are bugged altogether. Crew members never apparently gain any ranks in skills via live training. Yet, when they try to gain ranks via schools, they require much more coal to raise ranks in any said live-trained skills than in any non-trained skills. School training appears to work fine otherwise.

This might also be affecting attributes, though I can't say for certain.

**Comment by thindil** [comment]
Okies, here is few things, I will try explain ;)
1. About gaining experience: partially true, there is bug in stable version which prevent from gaining experience in melee combat. I was fixed it few days ago and soon fix will be available with new version.
2. Gaining experience in other situations works good, problem is somewhere else: 
- By live training crew members gain really small amounts of experience (compared to experience needed to gain new level). More technical info: skills are leveled from 1 to 100 and for each next level character need 50 * previous level experience (so from 4 level to 5 level is needed 200. In that situation pilot must fly 200 fields to gain this one level). Attributes needs even more. I'm not sure did there should be lowered amount of experience needed for next level. Maybe school is too good and teach skills too fast? I'm open for discussion about this ;)
- In stable version info about skills levels changing around every 20 levels, thus it may looks like nothing change ;) In development version skills have progress bars, which show bit better that they very slowly advancing. But still this can be unnoticeable. So, maybe after each gain in level add message, something like `[Name] learned a bit about [skill name]`? Again, good thing to start discussion :)

**Comment by ShinQuickMan** [comment]
Alright, with that info, and some more experience, I think I can give some opinions and critiques. Of course, these are based on the condition that I don't know what's intended/expected when it comes to the duration for each playthrough, and that most of these features (and others related ones) are still very much in development.

1. Live-training skills take way too long. You could play for hours, and gain no appreciable results to skill levels/ranks in any skill. Combat skills are especially difficult, given how much less frequent (and more dangerous) it is to stay in a prolonged fight.

2. School-trained skills are impractically expensive. Even one-hundred thousand coal won't gain a rank in any one skill.

3. By comparison, hiring a new crewmember is both a greatly significant timesaver and bargain, as they start with much higher ranks in skills than could be realistically gained via live or school training. Players could get a crewmember with master or even legendary ranked in several skills for ~20k coal, and even the most expensive ones (whom are often masters in many skills) cap at about ~80k.

As it stands, raising skills is a bit of a grind, and not worth the effort. With all that time and cash that it would take appreciably level up the starting team, one could instead hire a new hyper-competent squad five times over. Much like equipment, there's no reason to stick with an old crewmember if you could afford someone better (barring the captain, of course).

**Comment by thindil** [comment]
Ok, then maybe that: for now I can raise (only in development version) gaining combat skills and prices for hiring new crew members (I like this idea with higher level skills cost more than lower) and we will see how it will be works.
Other things (they are planned "soon" :) ) are negotiations in hiring new crew members, payment for crew, loyalty or ability to train skills on ship. This should change everything too.

**Comment by thindil** [comment]
Another progress report ;) I was raised gaining experience in combat, we will see now how it works. About change price: I did some test, yes this will raise price, just in that situation, there will be no room for other options which I was mentioned in earlier comment. Thus for now I will leave prices unchanged.
Summary:
- Bug with not gaining experience in combat is fixed
- Experience gained in combat is doubled (in development version)

We will see how this changes will affect game, especially new features in game arrive. For now I will close this issue, but if someone disagree with me, please reopen (or just leave comment) ;)
