### ISSUE TITLE
Crash when removing cabins and cargo bays when either are at capacity

### ISSUE THREAD

**Issue by ShinQuickMan** [thindil/steamsky#23]
See title. Not having a replacement for either prior to removal always results in a crash.

**Comment by thindil** [comment]
Hello and as usual, thank you for report, I'll look at this tomorrow.

**Comment by thindil** [comment]
Hmm, just tried to reproduce it and everything works ok for me, no crash. Could you, please give more details? Best if you can add message from error.log file.

**Comment by ShinQuickMan** [comment]
Maybe I jumped the gun a bit. I guess it must've been something else. Don't have the specific error message to give either. Sorry about that.

**Comment by thindil** [comment]
Ok, I will close for now this issue. There is one fix inside shipyard (maybe it was it). If you find this same problem again, please reopen this issue, comment here or just create new. Once again, thanks for help :)
