### ISSUE TITLE
Background is always grey

### ISSUE THREAD

**Issue by greenfork** [thindil/steamsky#28]
Hello, I have this kind of a screen.

![image](https://user-images.githubusercontent.com/20167110/45897714-91b9d880-bde0-11e8-94be-129f3e0ab3ea.png)

I use i3wm-gaps as my window manager, alacritty as my terminal emulator.

**Technical Info:**
 - OS: linux gentoo
 - Version: 4.14.65, x64

**Comment by greenfork** [comment]
My background is purely black 0x000000, I also use compton to make it a bit transparent. The color on the screenshot is apparently completely new.

Also, I have ncurses v6.1-r2 if that is useful.

**Comment by thindil** [comment]
Ok, thank you again for help and just last question: this gray color is whole time, even for discovered part of the map?
I will try check it tomorrow.

**Comment by greenfork** [comment]
Yes, I departed from the cyan "O" and didn't see anything else on the map at all.

**Comment by thindil** [comment]
Ok, I will try address all issues :)

1. urxvt - this terminal emulator is very *special*. It is something like Internet Explorer of terminal emulators :). Basically, it ignore most of standards (with colors, keys codes, etc). If I remember correctly urxvt require a lot of tweaking to work properly with ncurses based programs. Longer version of problems between ncurses and urxvt: http://invisible-island.net/ncurses/ncurses-urxvt.html

2. Background in tmux: yes, probably it is it. As I was wrote in linked issue before (https://github.com/thindil/steamsky/issues/15#issuecomment-381381179) if something change default setting for terminal colors, ncurses then can't change it back.

3. Whole background in one color, no visible changes between visited and not visited parts of map: I done some tests and looks like Gentoo set default TERM environment variable for all terminals (I was tested it on Konsole and Xterm too, this same problem). Normally it is `xterm` but on pure console (I was testing on Minimal Installation CD) it is set to `linux`. In this situation I'm afraid the only options are:
- Change default setting of TERM variable to `xterm-256color` . Should be ok, all modern terminal emulators support 256 colors at least.
- Remove completely this variable, so each terminal will be report self properly. But this may cause some problems, especially with more *exotic* emulators like termite, etc.
- Start game (and probably any ncurses program) with separated TERM variable. For example for the game it will be `TERM=xterm-256color ./steamsky`.

I will just try add something to prevent this crash when TERM=linux but that is all what I can do. Again, thank you for report and help and I'm sorry for problems.

**Comment by greenfork** [comment]
For alacritty I have `TERM=xterm-256color`, for pure terminal it is `linux`, just as you had it. Running tmux in both cases sets it to `screen`. I guess you can do something similar to `linux` variant.

Setting `TERM=xterm-256color` helps: 1) running in pure terminal, though I couldn't use numpad: both switched on and switched off states opened same kind of game menus; 2) running in alacritty + tmux: everything seems to work fine.

Thanks for the information about urxvt, it's interesting.

PS I guess the issue with all-one-color thing is worth documenting as it is an instant turn down for the game if you are unable to provide a stable fix for it.

PPS I rarely see an Ada repository with 6k commits, thanks for this experience.

**Comment by thindil** [comment]
About all-one-color: ok I will add this to README.md, should save other people some time.

Problem with numpad: my guess - `linux` terminal emulator don't support it correctly in ncurses (or in general?) and the only way to fix it is just change keyboard setting in game. I think I will add this info too to README.md

I prefer don't change TERM variable by the game - it may cause some problems on more *exotic* terminals (especially this one which are not compatible with xterm). But we will see, I need to this about this.

About large amount of commits: this just means that I put even one-line changes in separated commits :) Plus more than 2 years of development can produce some spam in logs :D
