### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [thindil/steamsky#3]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by thindil** [comment]
Hello.

Thanks for suggestion, I need to look closer to libyui. I have plans to made some changes to game UI (using [GtkAda](https://github.com/AdaCore/gtkada)) just for now they are "very long term goal" - for next stable version (3.0). At this moment I can't decide which exactly option to use (this is one of reasons why this is "long term goal" :) ):
1. Working on two versions of UI - TUI and GUI: which mean add GUI version of game.

 Advantage is that game will still be available in console too. 

Disadvantages: 
- more work than with one UI
- soon or later TUI version will be less advanced and limited than GUI version.
- harder to set whole development environment
2. Remove TUI version and work only on GUI.

Disadvantage is of course lack of support for console.

Advantages:
- Simpler, smaller code
- Can focus on one version of UI and polishing it (using all available options like using many fonts, images, multilanguage support, etc)
- Multiplatform support: GtkAda works on all mayor operating systems, when AdaCurses was probably tested only on Linux.
- Very easy to set development environment (just download whole Ada package from https://libre.adacore.com and go :) )
3. New option libyui ;) Just question is: did it is only available on Linux or works on different systems too?

Anyway, thanks again for suggestion and I'm open for discussion in that matter :)

Kind regards.

**Comment by thindil** [comment]
Ok, I was looking a bit at libyui and as I see it works only on Linux/BSD (maybe MacOS) systems. So, I'm afraid it isn't good option for project. I'm probably will stay with my earlier choices from comment above :)
