### ISSUE TITLE
Can not quit game during battle

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#30]
I did not find a option for quitting the game during battles. 
I can kill the process, but it would be nicer to be able to rage quit using a key or a button :)

![screenshot from 2018-10-10 19-53-42](https://user-images.githubusercontent.com/652603/46752561-3afc3c00-ccc6-11e8-9308-3b51b42b0264.png)

**Comment by thindil** [comment]
Hello, and thanks for suggestion :)
Now I start thinking which way it will be better done:
- Add separated button for quitting during combat
or
- Just add this same menu which is available on map.

For me, second option look better (this will remove then most buttons from combat too). What you think about it?

**Comment by thindil** [comment]
Yes, but this is not always visible (not on every windows manager under Linux, for example AwesomeWM and I3WM don't show this buttons). 
Ok, I think I will just made Menu available in combat too (and this "x" button too).

**Comment by thindil** [comment]
Ok, now should be a bit better :) Thank you again for this suggestion.
