### ISSUE TITLE
GUI elements resize when hovered

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#32]
Some GUI elements resize and push stuff around. Not super critical, but could be nice if was fixed.
![peek 2018-10-10 19-45](https://user-images.githubusercontent.com/652603/46752775-bfe75580-ccc6-11e8-9dc5-d9811011b797.gif)

**Comment by alkhimey** [comment]
![peek 2018-10-10 19-47](https://user-images.githubusercontent.com/652603/46752837-df7e7e00-ccc6-11e8-884e-6e8fa7b935cc.gif)

**Comment by thindil** [comment]
Hello agian and again thanks for report :)

Well, bit critical, because whole UI looks bit different than it should :) Not only it should not resize but should not have this white borders too :)

**Comment by thindil** [comment]
No, I'm still working on Linux (even Windows version is cross-compiled here :) ). Just under Fedora and with some custom themes I don't have that effects. I just need it test more under standard Ubuntu configuration :)

**Comment by thindil** [comment]
Ok, then this problem should be fixed too :) Thank you again for report.
