### ISSUE TITLE
Can not escape to wrold map after battle

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#33]
When winning or losing or escaping a battle, an "escape" button appears.

After clicking it, it disappears and nothing happens.

![screenshot from 2018-10-10 21-38-28](https://user-images.githubusercontent.com/652603/46758289-24111600-ccd5-11e8-884d-20b70c0df7c9.png)

![cantescape](https://user-images.githubusercontent.com/652603/46758505-a8fc2f80-ccd5-11e8-9caa-b46a65d785b4.gif)

**Comment by thindil** [comment]
As usual, hello and thanks for report :)

This happens always or only when you or enemy ship escape?

**Comment by thindil** [comment]
I was tried to reproduce this bug and simply can't. Button works for me, no matter did I or enemy ship escape. Maybe this is cause for this same reason like #31, #32 and #34?

**Comment by thindil** [comment]
As mentioned in #31 - this is fixed too (problem was running Linux binary directly not by script).
