### ISSUE TITLE
Tiles stretch too much on X axis

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#34]
Each UI tile cover 3 clickable coordinate values:
![cursor](https://user-images.githubusercontent.com/652603/46758626-f5e00600-ccd5-11e8-99bb-ef95a4519b05.gif)

**Comment by thindil** [comment]
Hello and standard thanks for report ;)

Just one question: did you changed size of map font in game settings?
For me it looks like game can't find proper fonts for some reason.

**Comment by thindil** [comment]
Almost robotic comment :) As mentioned in #31, this is caused by running game on Linux by binary not by starting script.
