### ISSUE TITLE
UI/UX: Selecting character goal behaves different than other menuses [more rfe than a bug]

### ISSUE THREAD

**Issue by VedVid** [thindil/steamsky#35]
**Describe the bug**
It's impossible to expand goals (during character creation) using keyboard - it's necessary to use mouse.

**To Reproduce**
1. Start [New Game]
2. Press [tab][tab][tab] to highlight "Character goal"
3. Press [enter] to enter submenu
4. Try to select goal other than "Random" using only keyboard

**Expected behavior**
I can use keyboard to choose any other option in character creation screen, so I expected that pressing [enter] would expand "submenuses", but I have to click mouse to do it.

**Technical Info:**
 OS: Windows 10 x64
 Version: 3.0.3

**Comment by thindil** [comment]
Hello and thank you for report.
I will take a look on it tomorrow, should be easy to fix.

**Comment by thindil** [comment]
Ok, this one should be fixed (I will release new game version with this fix on Sunday). Thanks again for report :)

**Comment by VedVid** [comment]
Hello, and no problem, I'm always glad to help :)
