### ISSUE TITLE
Auto-resizing window makes it hard to exit character creation screen in specific curcumstances.

### ISSUE THREAD

**Issue by VedVid** [thindil/steamsky#36]
**Describe the bug**
During character creation, window resizes automatically to fit to content. In some circumstances, it results "Start game" button lying out of the screen.

**To Reproduce**
1. During creating new character to start new game, choose "Undead" or "Drones" as character faction
2. See error

**Expected behavior**
I'd like to see menu on screen. "Start game" and "Exit menu" could be positioned at the top of screen, below options - just not depend on "Faction info" and "Career info" boxes that are  on the side of screen already. Allowing to move window would be working workaround as well.

**Technical Info:**
 OS: Windows 10 x64
 Version: 3.0.3

**Additional context**
I have widescreen 1920x1080 monitor. This bug may not be an issue for users with more vertical-oriented monotors.

![image](https://user-images.githubusercontent.com/16949680/51087840-82c4b080-1758-11e9-8e72-38f0f2204c0d.png)

**Comment by thindil** [comment]
Hello and again thank you for report :)
Ugh, right, it looks ugly, I will try fix it in week. The game should looks good on any monitor :)

**Comment by thindil** [comment]
Ok, so this is fixed too, again, thank you for the report and I'm sorry for problems.

**Comment by VedVid** [comment]
No need to be sorry! 

Unfortunately, this change causes #38
