### ISSUE TITLE
Lack of colon after "Version" in bug report template // OS has very own colon

### ISSUE THREAD

**Issue by VedVid** [thindil/steamsky#39]
**Describe the bug**
```
**Technical Info:**
 - OS: [e.g. iOS]
 - Version [e.g. 22]
```

**Comment by thindil** [comment]
Again, thanks for report, I will fix this typo tomorrow :)

**Comment by thindil** [comment]
Ok, at least this issue not need to wait few days for release :) As usual, thank you very much for report.
