### ISSUE TITLE
Crash on selecting "Repair ship" with item in inventory

### ISSUE THREAD

**Issue by almostmist** [thindil/steamsky#4]
Hello and thanks for making this game! It seems really promising, but it just crashed during my first playthrough.

1. Entered combated with (o)rders menu
2. Ship hit
3. Select the one unassigned crew member I have (i.e., not the Engineer, Pilot, or Gunner) with (c)rew info
4. Give order "Repair Ship"

Then crash.

Judging from the error log, it seems to be that I'd put one (1) basic rations in that crew member's inventory before entering combat, thus making her inventory full...thus preventing her from repairing somehow. Please see below.

Thanks!

`2017-11-05 06:00:59
Version: 1.8
raised CREW.CREW_NO_SPACE_ERROR : Maleyaleg don't have free space in own inventory.
Call stack traceback locations:
0x55597fac5b4d 0x55597fac8438 0x55597fc099d4 0x55597f94d909 0x55597f94af78 0x7fd3aa6561bf 0x55597f94afd8 0xfffffffffffffffe`

**Comment by thindil** [comment]
Hello and thank you very much for report :) Indeed, to start repairing ship, crew members must take repair tools to their inventory and this crash is caused by lack of free space in it. I will check it tomorrow.

**Comment by thindil** [comment]
Ok, should be fixed now, if not, please reopen issue again.

**Comment by almostmist** [comment]
Related crash today perhaps.

1. Crew info screen
2. "Press F2 to show crew member inventory"

Crashes upon pressing F2.

Error.log

```
2017-11-07 17:56:53
Version: 1.8
raised CONSTRAINT_ERROR : crew-ui.adb:736 overflow check failed
Call stack traceback locations:
0x55fa53e9bb3d 0x55fa53e9d6e5 0x55fa53f0f10b 0x55fa53f3049e 0x55fa53c739bd 0x55fa53c71018 0x7f128dc951bf 0x55fa53c71078 0xfffffffffffffff
```

Tried addr2line again, but no useful output.

**Comment by thindil** [comment]
OK, I'm reopening this issue again, just as I see, it is something new :) This have a bit useful output, just few questions:
- Did this crew member on which inventory crash was occur was something in inventory?
- If was something, did you remember what and how many?
- It was NPC inventory or player character inventory?

**Comment by almostmist** [comment]
* Nothing was in the crew member's inventory.
* Play character inventory

**Comment by thindil** [comment]
Ok, just one question this time ;) It happens every time or only once and never again? I'm trying to reproduce this crash just my game is stubborn and don't want do it :)

**Comment by almostmist** [comment]
I was able to reproduce this twice. I'm not home right now, but I'll try again in a new game when I get back.

**Comment by thindil** [comment]
Ok, thank you very much again for help and no hurry :)

**Comment by almostmist** [comment]
Cannot reproduce in a new game.
