### ISSUE TITLE
Using PageUp and PageDown in character screen behaves like Home / End - it just scroll list of options to the start / end.

### ISSUE THREAD

**Issue by VedVid** [thindil/steamsky#42]
**Describe the bug**
As in title.

**To Reproduce**
1. Go to Character Screen
2. Move to the "Character Faction" (used in this example) or "Character Career"
3. Try to "scroll" options via PageUp and PageDown
4. Observe: every time when one use PageDown, Inquisition appears; every time when one use PageUp, Poleis appears.

**Expected behavior**
Change chosen option like using arrows - one per click.

**Technical Info:**
 - OS: Windows 10 x64
 - Version: 3.0.4

**Additional context**
Arrow keys works well enough, PageDown and PageUp could be used to scroll text, like I described in #41 :P
 
Btw, please tell me, if my suggestions crossed the line between "being helpful player" and "being annoying prick that wants to control development" :<

**Comment by thindil** [comment]
As usual, thanks for report :) And no worry, you are very far from this "annoying" point :) Lack of some keyboard shortcuts is still a bug which need to be fixed.

**Comment by thindil** [comment]
And we have small problem. I was done some tests and Page Up and Page Down in that list works bit different :)
If there is small amount of entries to select it is true, they works as Home/End buttons. But if there is more entries than can be on screen (very long lists) they simply scroll to next "page" of list.
So, I think I will left it unchanged for now, may be useful in future. If you disagree with me, please reopen this issue or start new on this same topic :)
