### ISSUE TITLE
[CRASH] trades-ui.adb:212 range check failed

### ISSUE THREAD

**Issue by RandomErrorMessage** [thindil/steamsky#44]
**Describe the bug**
Game crash on highlighting specific item in trade menu

**To Reproduce**
[bugged-save.zip](https://github.com/thindil/steamsky/files/3337020/bugged-save.zip)
Attached save file, enter trade menu at currently docked hub, highlight Steel Sickle, crash.

**Technical Info:**
 - OS: Linux
 - Version: 3.8-dev

**Additional context**
Version: 3.8
Exception: CONSTRAINT_ERROR
Message: trades-ui.adb:212 range check failed
-------------------------------------------------
[./steamsky]
Trades.Ui.Showitemtradeinfo at trades-ui.adb:212
0xc1f066 gtkada__builder__builder_callback__first_marshallerXn at ???
[/tmp/.mount_steamsUxGzgP/usr/lib/libgobject-2.0.so.0]
0x7f2ef9c92d7a
0x7f2ef9c9fdbf
0x7f2ef9ca7986
0x7f2ef9ca7e10
[/tmp/.mount_steamsUxGzgP/usr/lib/libgtk-3.so.0]
0x7f2efb51500e
0x7f2efb518800
[./steamsky]
Trades.Ui.Searchtrade at trades-ui.adb:461
0xc1f066 gtkada__builder__builder_callback__first_marshallerXn at ???
[/tmp/.mount_steamsUxGzgP/usr/lib/libgobject-2.0.so.0]
0x7f2ef9c92d7a
0x7f2ef9c9fdbf
0x7f2ef9ca7986
0x7f2ef9ca8206
[/tmp/.mount_steamsUxGzgP/usr/lib/libgtk-3.so.0]
0x7f2efb387cc7
0x7f2efb38bb03
[/tmp/.mount_steamsUxGzgP/usr/lib/libgobject-2.0.so.0]
0x7f2ef9c92d7a
0x7f2ef9ca04c5
0x7f2ef9ca7986
0x7f2ef9ca8206
[/tmp/.mount_steamsUxGzgP/usr/lib/libgtk-3.so.0]
0x7f2efb385df3
0x7f2efb38f388
[/tmp/.mount_steamsUxGzgP/usr/lib/libgobject-2.0.so.0]
0x7f2ef9c94b32
0x7f2ef9c92f17
0x7f2ef9ca77e8
0x7f2ef9ca8206
0x7f2ef9c94b32
0x7f2ef9c92f17
0x7f2ef9ca77e8
0x7f2ef9ca8206
[/tmp/.mount_steamsUxGzgP/usr/lib/libgtk-3.so.0]
0x7f2efb3e62d2
0x7f2efb3e63c8
0x7f2efb3e687d
0x7f2efb3e89a1
0x7f2efb38b4c2
0x7f2efb40627c
[/tmp/.mount_steamsUxGzgP/usr/lib/libgobject-2.0.so.0]
0x7f2ef9c92ce7
0x7f2ef9ca04c5
0x7f2ef9ca7104
0x7f2ef9ca7e10
[/tmp/.mount_steamsUxGzgP/usr/lib/libgtk-3.so.0]
0x7f2efb52e7ea
0x7f2efb54cdba
0x7f2efb54ff29
0x7f2efb40627c
[/tmp/.mount_steamsUxGzgP/usr/lib/libgobject-2.0.so.0]
0x7f2ef9c92d7a
0x7f2ef9ca04c5
0x7f2ef9ca7104
0x7f2ef9ca7e10
[/tmp/.mount_steamsUxGzgP/usr/lib/libgtk-3.so.0]
0x7f2efb52e7ea
0x7f2efb403e77

**Comment by RandomErrorMessage** [comment]
It seems like this is related to a market running out of money.

**Comment by thindil** [comment]
Hello, and I'm sorry for problems. Yes, you have right, it crash exactly when base don't have enough money to buy one more selected item. I just came across of this bug too, few days ago, thus should be fixed in 9a52b070712e2a4a17b8fe17b5dd18f0aad6c52c commit. Anyway, thank you very much for your report. At this moment the only way to fix it (or workaround) in 3.8 version is to not go too low with money in base. I will close this issue as solved, if you disagree, feel free to reopen it :)
