### ISSUE TITLE
Crafting-related crash

### ISSUE THREAD

**Issue by Asmageddon** [thindil/steamsky#46]
I was deconstructing a gunsmith kit during a standstill battle in the hopes that it would yield bronze plates with which I could finish upgrading my engine to escape. Alas, after 5 days of eternal combat, this happened:

```
:42:56
Version: 4.3
Exception: CONSTRAINT_ERROR
Message: crafts.adb:350 range check failed
-------------------------------------------------
[./steamsky]
Crafts.Manufacturing.Resetorder.12592.Constprop at crafts.adb:350
Crafts.Manufacturing at crafts.adb:650
Game.Updategame at game.adb:442
Combat.Combatturn at combat.adb:1379
Combat.Ui.Nextturn at combat-ui.adb:926
[/usr/lib/x86_64-linux-gnu/libgtkada.so.18]
0x7ff5ec15d28b
[/home/asmageddon/Workspace/git/steamsky/lib/libgobject-2.0.so.0]
0x7ff5e9d9ad7a
0x7ff5e9da7dbf
0x7ff5e9daf986
0x7ff5e9dafe10
[/home/asmageddon/Workspace/git/steamsky/lib/libgtk-3.so.0]
0x7ff5eb634fca
[/home/asmageddon/Workspace/git/steamsky/lib/libgobject-2.0.so.0]
0x7ff5e9d9ad7a
0x7ff5e9da7dbf
0x7ff5e9daf104
0x7ff5e9dafe10
[/home/asmageddon/Workspace/git/steamsky/lib/libgtk-3.so.0]
0x7ff5eb404f4c
0x7ff5eb40672b
0x7ff5eb657e18
0x7ff5eb657f0f
0x7ff5eb50e27c
[/home/asmageddon/Workspace/git/steamsky/lib/libgobject-2.0.so.0]
0x7ff5e9d9ad7a
0x7ff5e9da84c5
0x7ff5e9daf104
0x7ff5e9dafe10
[/home/asmageddon/Workspace/git/steamsky/lib/libgtk-3.so.0]
0x7ff5eb6367ea
0x7ff5eb50be77
0x7ff5eb50d8cc
[/home/asmageddon/Workspace/git/steamsky/lib/libgdk-3.so.0]
0x7ff5eb0ddc40
[/home/asmageddon/Workspace/git/steamsky/lib/libglib-2.0.so.0]
0x7ff5e98b1fa5
0x7ff5e98b2216
0x7ff5e98b2470
[/home/asmageddon/Workspace/git/steamsky/lib/libgtk-3.so.0]
0x7ff5eb50cc23
[./steamsky]
Steamsky at steamsky.adb:131
Main at b__steamsky.adb:2015
[/lib/x86_64-linux-gnu/libc.so.6]
0x7ff5e8aeb099
[./steamsky]
0x5652c227aa48 _start at ???
0xfffffffffffffffe
```

**Comment by thindil** [comment]
Looks like few bugs here :)
1. Crash, yes, I will try fix it as soon as possible.
2. Again, documentation: deconstructing don't give materials, it only give crafting recipe for selected item. Probably this need to be clarified in help.
3. 5 days long battle? I definitely did something wrong :)
And as always, thank you very much for your report and I'm sorry for problems.

**Comment by thindil** [comment]
Ok, I'm trying to recreate this crash and I have bad luck with it. If it is possible (and you remember), could you tell a bit more about this crash? Like:
1. Did someone in crew died in this moment?
2. Did someone was go on break in this moment?

**Comment by Asmageddon** [comment]
@thindil Yeah, the battle took 5 days because a tiny drone was faster than me, but incapable of dealing damage. It only hit once an hour or so, and then did no damage.

I don't think anyone in crew died, because I kept checking food/water supplies, and not sure what else would kill them.

Not sure because I was just holding space to pass turns. I have the vaguest notion that maybe the tool used to deconstruct broke? Maybe I saw that in the message subliminally without paying proper attention?

Sorry for posting such a vague bug with incomplete details x.x It seems fairly minor so please don't worry about it too much :-P

**Comment by thindil** [comment]
It is ok, I should apologize for releasing the game with bugs :) Anyway, I think I can fix it that at least this crash will not happen again. I just need to sit down a bit and trace what exactly caused it. Plus of course, update in-game help that deconstruction don't give materials :)

**Comment by Asmageddon** [comment]
@thindil I think it'd be cool if "to learn the recipe" was specified, and I'd personally like it to give materials back too.

**Comment by thindil** [comment]
I think I will later change it name to "learn recipe for " and maybe add normal "deconstruction" option to recover materials?

**Comment by Asmageddon** [comment]
@thindil What about parametric recipes, with one for "Study ____", and another for "Deconstruct ____" ?

**Comment by thindil** [comment]
Yes, something like this was in my mind :) I will need to think a little about it.

**Comment by thindil** [comment]
Ok, so this should be fixed now and release should be very soon :) Thank you again for your report and I'm sorry for problems.

**Comment by ChrisEdBurt** [comment]
I encountered a crafting bug as well, I don't try to craft anything most of the time as it is almost guaranteed to crash when I do. Here is the error log.

2020-01-31 02:24:27
Version: 4.6
Exception: CONSTRAINT_ERROR
Message: bases.adb:208 range check failed
-------------------------------------------------
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\steamsky.exe]
Steamsky.Updatepath at bases.adb:208
Steamsky.Updatepath at game.adb:469
Steamsky.Updatepath at ships-movement.adb:173
Steamsky.Updatepath at maps-ui-handlers.adb:391
0x8cc001 steamsky__updatepath.4595 at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgobject-2.0-0.dll]
g_closure_invoke at gclosure.c:768
signal_emit_unlocked_R at gsignal.c:3549
g_signal_emit_valist at gsignal.c:3305
g_signal_emit at gsignal.c:3361
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgtk-3-0.dll]
0x66489406 gtk_style_set_property at ???
0x66489468 gtk_style_set_property at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgobject-2.0-0.dll]
_g_closure_invoke_va at gclosure.c:831
g_signal_emit_valist at gsignal.c:3214
g_signal_emit at gsignal.c:3361
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgtk-3-0.dll]
0x664872f2 gtk_style_set_property at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libffi-6.dll]
0x6b745075 ffi_call_win64 at ???
0x6b744cf3 ffi_call at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgobject-2.0-0.dll]
g_cclosure_marshal_generic_va at gclosure.c:1561
_g_closure_invoke_va at gclosure.c:831
g_signal_emit_valist at gsignal.c:3214
g_signal_emit at gsignal.c:3361
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgtk-3-0.dll]
0x6652bff8 gtk_style_set_property at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgobject-2.0-0.dll]
g_cclosure_marshal_VOID__BOXEDv at gmarshal.c:1950
_g_closure_invoke_va at gclosure.c:831
g_signal_emit_valist at gsignal.c:3214
g_signal_emit at gsignal.c:3361
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgtk-3-0.dll]
0x6652952b gtk_style_set_property at ???
0x6652a8a9 gtk_style_set_property at ???
0x6652d3ff gtk_style_set_property at ???
0x66501076 gtk_style_set_property at ???
0x66695c49 gtk_style_set_property at ???
0x6656f841 gtk_style_set_property at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgobject-2.0-0.dll]
_g_closure_invoke_va at gclosure.c:831
g_signal_emit_valist at gsignal.c:3214
g_signal_emit at gsignal.c:3361
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgtk-3-0.dll]
0x66699540 gtk_style_set_property at ???
0x6656d1ab gtk_style_set_property at ???
0x6656ed2e gtk_style_set_property at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgdk-3-0.dll]
0x70eeb681 gdk_device_manager_win32_finalize at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libglib-2.0-0.dll]
g_main_context_dispatch at gmain.c:3122
g_main_context_iterate.isra.10 at gmain.c:3808
g_main_loop_run at gmain.c:4002
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\libgtk-3-0.dll]
0x6656e0bb gtk_style_set_property at ???
[C:\Users\***\AppData\Local\Programs\Steam Sky\bin\steamsky.exe]
Steamsky.Updatepath at steamsky.adb:131
Steamsky.Cold at b__steamsky.adb:2067
__tmainCRTStartup at crtexe.c:339
mainCRTStartup at crtexe.c:223
[C:\Windows\System32\KERNEL32.DLL]
0x7ffd4d951fe2
[C:\Windows\SYSTEM32\ntdll.dll]
0x7ffd4db4ef8f

**Comment by thindil** [comment]
Hello, thank you for the report and I'm sorry for problems. Unfortunately, as a bug in the development version, release of fix for this one will be a bit later (with release 4.7), unless you will be using Continuous Integration version. Then it should be fixed in next 2-3 days :)

**Comment by ChrisEdBurt** [comment]
That`s not a problem for me, I have played both versions and the most up to date one is super stable from what I can tell.
I would love to be able to move my save from the dev up to current but alas, the current doesn`t have Agora. I like being able to get cheap recruits :P so I`ll stay with the dev for now.

**Comment by thindil** [comment]
Ah, then ok, just warning that the development version can have a lot of bugs :) In the stable version, you can reduce prices for recruits in difficulty menu, by reducing all prices. Maybe it should be a separated setting?

**Comment by ChrisEdBurt** [comment]
I have noticed just a few bugs with the dev version, it can be a little annoying at times but the game is more than fun enough to make up for it.

Yes, I have done that at the start of the game but I like getting a super cheap recruit with basically no skills in any categories and making them into whatever I like. Not related to crafting but does using weapons increase a characters strength stat, I've played a great deal of time on my dev game and their 4 main attributes seem to be increasing very slow, if at all.

**Comment by thindil** [comment]
It should increase. Just probably need to be adjusted. And if you encounter any problem or bug, feel free to open new issue about it ;) Soon or later the development version will be presented as stable, so better to fix them now than later :)

**Comment by thindil** [comment]
Ok, at least this one bug should now be fixed in the development version. Thank you again for the report and I'm closing this issue again :)
