### ISSUE TITLE
crashes after buying items at shipyard

### ISSUE THREAD

**Issue by Alien-AV** [thindil/steamsky#47]
Apparently it happens after I've bought the battering ram.
Crash is at line https://github.com/thindil/steamsky/blob/master/src/ui/bases-shipyardui.adb#L111. It references battering rams `damage`, however in other places relevant to battering ram I see `damage2` mentioned, I'd assume that's the issue.

**Comment by thindil** [comment]
Hello, and yes, looks like, I will try fix it ASAP. Thank you very much for the report.

**Comment by thindil** [comment]
Ok, this one should be fixed now. New stable version will be released tomorrow. Again, thank you for the report.
