### ISSUE TITLE
Inventory window doesn't show properly, most of the interface is not drawn, flickering on and off.

### ISSUE THREAD

**Issue by Alien-AV** [thindil/steamsky#48]
These are the sort of messages appearing in the console when it happens:

```
(steamsky.exe:18732): Gtk-WARNING **: drawing failure for widget `GtkBox': invalid matrix (not invertible)
(steamsky.exe:18732): Gtk-WARNING **: drawing failure for widget `GtkStack': invalid matrix (not invertible)
(steamsky.exe:18732): Gtk-WARNING **: drawing failure for widget `GtkOverlay': invalid matrix (not invertible)
(steamsky.exe:18732): Gtk-WARNING **: drawing failure for widget `GtkPaned': invalid matrix (not invertible)
```

**Comment by thindil** [comment]
Hello,
With this one will be a bit more problems. It happening every time or just in some occasions?
And what operating system? Window or Linux?
Of course, thank you for the report and I'm sorry for problems.

**Comment by Alien-AV** [comment]
Happens all the time in the inventory screen.
Windows.

Thanks.

**Comment by thindil** [comment]
Yes, now I can reproduce, let's see did I can fix it too, looks very weird for me.

**Comment by thindil** [comment]
This problem should be fixed too. Thank you for the report and if you want to add something about this issue, feel free to open it (same as any other). New stable release with this fix will be released tomorrow (in around 24 hours).
