### ISSUE TITLE
A large batch of feedback.

### ISSUE THREAD

**Issue by Asmageddon** [thindil/steamsky#49]
Hi, I'm sorry that it took me so long, and I'm secondarily sorry for *how long* the feedback itself got. I tried to organize it some, but... longer trains of thought often elude me.

Also, I tend to be fairly critical, so please don't take the amount of things I find faulty to be an indicator of "your game is no good". I definitely think you've got a neat start of something cool here. Elsewise, it'd have never caught my eye.

Anyway, here it is:

-----

## Overarching issues:

 1. The game loop is basically a grind of trade trade trade, upgrade ship/crew roster

 2. The most optimal actions are the least rewarding, e.g. trading

 3. Progression is very linear, there's little choice, mainly just better vs worse, and it all
   reduces to the single axis of making more money to fund it all

 4. Combat lacks nuance, it feels like there's essentially four possible outcomes:
   You can beat the enemy, you can escape, you can stalemate(rare, vs melee/with high evasion), you cannot survive.
   With the likely choice being predetermined based on ship and crew, which, again, is better vs worse, not
   to mention you have no way of telling how strong you are until you either die or live.

 5. The world isn't very interesting, it's just disembodied bases floating around,
   without any patrols or traders moving around giving semblance of life, islands,
   weather conditions...

 6. There's a lot of content that doesn't have a particular niche in the game, or is just a variant of other content.

 7. The UX kinda sucks. Crew/inventory management is very uncomfy, screens reset when you buy/sell/change something,
   you need to reopen the base menu everytime, the screen takes a while to re-render, there's no time indicator...

### Progression and combat

I think that what the game needs is, first and foremost, a better core gameplay loop, one that
doesn't reduce to straight up farming more money, and where combat doesn't reduce to optimizing the `enemy_ehp / my_dpt >> my_ehp / enemy_dpt`
equation, where progress instead requires some degree of planning and/or opportunity.
I'm pretty sure right now [Lanchester's Laws](https://en.wikipedia.org/wiki/Lanchester%27s_laws) describe and predict combat to the letter.

I think that can be accomplished by making money important to stay afloat, but instead delegating progression to, say, for starters, faction/station reputation unlocking new stuff, opportunity hunting, figuring out which upgrades to install on your stuff, salvaging different gear from defeated ships from other factions, or just finding it out there in the wild in ruins.

E.g. instead of a single, easily optimized axis, you diversify into different, partially independent axes of progression.

Ideally, you should also make the progression less vertical, and more horizontal, so pursuing one axis doesn't just up your entire powerlevel, but rather gives you different options.

There also needs to be more tactical input from the player, as well as strategical input in planning
(currently it's just "more guns and armor = stronger, more engines = survive", perhaps with limit on the amount of guns and/or cargo to facilitate build diversification.

What if you had stuff like food spoiling, and refrigerated cargo for it, higher storage liquid-only tanks, etc. Different calibers being better/worse against armor/part/hull, engines that can use different fuel, parts that do automated processing and/or boost specific recipes or recipe types, self-repairing materials for ship component material, rare upgrades, etc.

I also think that some way to amortize the benefit of "more guns" is needed. E.g. recoil, which reduces accuracy as it accumulates, penalizing burst-firing in the long run, especially if you also have instability from enemy hits to cope with. Ideally, more guns should be a way to fit more variety for adaptability rather than solely more dakka.

### The world

I try to avoid just posting ideas as opposed to general feedback, so as to not cramp people's vision, but alas here we are, sorry.

What if instead of nothing but disembodied stations and static ship "events", the world was filled with floating islands of varying sizes (could be done with just background color plus symbols like: ◢◣◤◥◆). Visually, on top of islands, you could place all sorts of things: Forests, mountains, different bg to indicate meadow/desert/water - perhaps even make them possible to interact with(chop some wood when drifting in an emergency with no fuel, gather some dirty water, etc)

Gameplay-wise, I think it'd be neat if stations were significantly reduced in (market) size, with cities being the big time stuff, and perhaps each with multiple "industries", e.g. Agricultural+Industrial, Mining+Refining, etc.

You could eventually also add things like temporary air currents, hidden locations like hideouts, stashes, air creature lairs, ruins.

Also, give the player some sight radius around their position, rather than uncovering one square at a time. Shadows of islands could be visible at 2x the fog of war range, as they're big, noticeably stuff.

Furthermore, factions need to be expanded on somewhat: Currently you essentially have two: "Poleis" and "who cares", because they're simply too insignificant. What if instead you had regions with a dominant faction, plus some bases/embassies/etc. from other factions?

You could gradually give factions some randomized traits(like warlike, thrifty, scavengers, high-tech) to vary them beyond their names.

### Activities

First off, is the hierarchy of what's the most worth doing - ideally, it should align with what's fun, and vary from time to time to prevent monotony.

Second, I think currently they're mostly unengaging: For trading, I liked what Starsector did, namely: It had a base unit of each resource (though it was (almost?) always 200), in which the "markets" operated. E.g. every 200 below demand is a shortage, every 200 above demand+some safety margin is a surplus, which affects prices, mainly in increments of the supply/demand being filled/drained. Of course, your trading, as well as that of supply convoys(which you could raid to further affect things) affected these.

For combat, a big part of what made FTL work was that while the hull health kept ticking down, you could repair individual sections, which enabled their destruction and tactical depth - what do you keep down on enemy ship, what do you keep up on yours? Steamsky doesn't have that crew/repair management, and I really think it should.

For mission, simple text adventure kinds of games, perhaps using crew's skill checks, cargo or modules, etc. could be nice, albeit also a lot of work.

### Content

I think you should streamline items and ship components. E.g. no repair kit items, just material, instead of 1000 ship parts, have the general type(small/medium/large, caliber, type) with upgrade slots for material/ and part-dependent  subcomponents/upgrades. Instead of presenting all at once, have randomized selection at bases so there's an aspect of opportunity hunting.

For example, you could have it as: Raw, Processed, Product, Scrap items, maybe with extra generic components of various kinds.

Also do something else than weaker/stronger with materials: Give them unique benefits and drawbacks, like say, reduced/increased efficiency in terms of: visibility, weight, module function, special properties like really cheap/fast repair, or even self-repair(living wood?), reactive defense against larger calibers, etc. etc.

## Individual feedback

 * Bug: Standstill battles(e.g. melee that can't hit you or out of ammo vs broken gun) should end eventually, perhaps in any case when a battle takes too long, it ends because of, say, "low combat readiness"

 * Bug: Crash when hiring someone tied to the line `Hide(Gtk_Widget(Get_Object(Object, "negotiatewindow")));` at 235 in `ui/bases-recruitui.adb`
    * There's a secondary crash afterwards too, but at least having the new crewmember is saved \^\^`

 * Bug: Crash when delivering medicines for a price and you're out of cargo space. Another point in favor of credit/higher denomination currency?

 * Bug: If you move while the Dock/Close dialog is open, it remains open when away from the base

 * Bug: I got ambushed by an undead ship, went into ship screen, enabled second engine, set to escape, and ran away, the next turn
   button disappeared, but I did not otherwise go to map

 * UX: there needs to be a way to travel using the mouse that doesn't involve having to move to the faux-numpad, and of waiting without setting destination
   to current tile. Also, setting with speed set to full stop should wait, just show buttons in red

 * UX: Columns in install/remove module for type/size/material

 * UX: Don't automatically reset category/search when buying/selling. Also don't disable the close button(As in clicking it with mouse)

 * UX: Exiting a station screen should go back to the station menu

 * UX: Top bar buttons for going to the station menu(same as location of "Close [Escape]" button), second for going back to the
   last visited station screen,

 * UX: Tooltips can be rendered partially offscreen when hovering over UI items near the left or bottom sides of the screen

 * QoL/UX: "Buy all" button
 
 * QoL/UX: If you cannot buy/sell all, the button should be replaced with "Buy <max possible>"

 * QoL: The ability to set certain goods as auto-stock, e.g. buy up to and don't sell below X food, Y water, Z charcoalium and V repair kits, also reserve cargo space for them.
 
 * QoL: What about a trade window column with colored Unicode symbols for whether the current base is an importer, exporter, producer, consumer of a good. E.g. all stations consume food/water, most probably have some use for ammo/etc.

 * QoL: Add convenient display of derived stats, such as:
    * Effective top speed of your ship, since how do you even derive it on your own?
    * Price/weight ratio for cargo, impact of a good's weight on your travel speed.

 * Content: Skillbooks should be rare, individual items, where buying one is notable, not just yet another thing to buy in bulk
    * Overall, a lot of content is just... "one among many", almost meaningless individually

 * Balance/QoL: The currency taking cargo space makes for some... uncomfortable trading until you figure out that you need to buy adamantite saw/sickle to compress your charcoalium 1:25 by weight. I propose either/both of two solutions:
    * Rare metals/minerals with minimum value variation as secondary currency to complement charcoalium alone. Could be silver/gold, or refined orichalcum, adamantite, etc. bars
    * Individual factions having their own weightless credits, with different factions respecting friendly faction credits, with slightly different exchange rates depending on economy strength/relations, dunno.

 * Balance: The profitability of different actions in the game should be the other way around: Why would piracy exist if trading was 1000x more profitable? Why are limited opportunities like missions not vastly more profitable than trade? Why are profit margins on trading still so high when realistically everyone would jump on the opportunity? Why is there no taxes/tarrifs that might dig into the profitability? You can basically buy anything and sell anything anytime for profit or worst-case breaking even, there's little to no nuance

 * Balance: IMO, crew hiring costs need to be adjusted: Basic, no-skill crew should imo be mostly affordable to a player who just started, and crew with a ton of skills shouldn't scale in cost with all of them - you usually only use 1-2 skills per crew member, so what if their contributions were something like 100% for top skill, 60% for 2nd, 40% for 3rd, 20% for the rest each?
    * Perhaps set prices to less than the equivalent of the cost of training, to give merit to hiring higher end crew as opposed to just training the one desired skill?

 * Balance: Shouldn't variation in price be higher for goods that are more valuable? Or at least ones that are both valuable AND heavy
    * Price of objects should be tied to the price of the materials they're manufactured from, so adamantium saw/sickle isn't so absurdly weight-efficient

 * Balance/QoL: Station should have goods that they don't produce for sale, just in more limited quantities, at less favorable prices, and less reliably in case of less common goods

 * Instead of having the "Profit" column be set to the good's price or where it as bought by default, show how much the current price differs from the base price, to more intuitively indicate whether a good is cheap or expensive at a given place.

 * Custom difficulty needs a custom formula for evaluating point gain. How is 1% enemy damage in any way offset by setting upgrade costs to 200% when now the only thing you need to get upgrades is time? \^\^` I think it'd be better if you had Very Easy/Easy/Medium/Hard/Very Hard with fixed values, IMO. Maybe over a few axes like: Economy, Combat, Politics/Reputation.

**Comment by thindil** [comment]
First of all, you don't need to apologize for delay :) It is not a job so here are no deadlines :)
Critique - good, constructive critique, like your is always welcome, especially if it points to problems on which I'm blind.
Funny fact: many of your propositions are on my very long TODO list :) At least I can better prioritize them :) Some examples:
* Guns in combat:
1.  I want to made that big guns will require more crew to operate. Less gunners = gun shoots less often.
2. Big guns should shoots a much less often than small guns - like in real life. Which mean big guns may need better gunners if you want to hit enemy.
3. Different types of ammunition. So one type will better works against armored enemies, explosives for example do less damage but easier to hit, etc.
* Bases and connections between them. I want to connect in any way bases between self - so for example missions will be less random, same as asking for events or new bases.
* Spoiling food, containers, yes, they are on the list :)
Generally I want to add that player's actions have more impact on world or even only on his/her future in-game.
Just to say something about TODO list - at this moment it have around 400 positions - from very short and simple things like new items to complex like crew personality, etc. I probably should publish it somewhere so people will stop wasting time writing them :)

Bugs, suggestions: of course, I will start fixing them as soon as possible. At least this which are possible (this off-screen rendering tooltips is good example: as far I remember it is bug in GTK which I was trying to fix earlier too). As usual, I'm sorry for the problems.

And one thing: if you don't mind, after fixing all bugs/suggestions I plan to close this issue (but not comments to it). Reason: this general feedback can take very long to reach. I will just add missing propositions to my TODO list :) But of course, I'm open to discussion in that matter too. For now I just start to focusing on this worst things :)

**Comment by Asmageddon** [comment]
Hey, no worries.

If I can feature request some priorities, what about the fog of war and island additions? I feel like it'd make the world much prettier, and a better theme always enhances the rest of all. And the streamlining of items. Perhaps with ammo you could even have personal/low/high caliber, with in-between calibers using say, 2xLow caliber instead of 1x ?

Anyway, I'll try to check in on the game some times. If for any reason you'd particularly like to summon my eye just ping me :-)

**Comment by thindil** [comment]
Islands - I have another, similar idea, currently on hold, because it will need a lot of work. Probably soon or later I will back to it. Generally speaking, I must add history/description of the world to the game, this probably will explain why here are only "bases".
Fog of war and lack of it: main reason is that one square on map is (if I remember correctly) around 100 miles. Thus, this probably will be done by raising size of whole map, so each cell will be a just smaller piece of the world. Probably will be "on the table" very soon.
Streamlining items - I will check it. I think I have something similar in my TODO list.

And just warning - all these changes will appear in stable version in a few months, thus please don't expect anything too fast :) Maybe except fixing errors and balancing :)

**Comment by Asmageddon** [comment]
I don't think you need to keep the distances so large - it is, after all, a fictional rather than real world. I don't see what would be wrong with reducing current cell size to just, say, two miles each while maintaining the current on-map distances.

You could even start with islands as being something that's just rendered under parts of the world, rather than interactive in any way.

I really do think that steamsky could benefit a lot from giving the world some "physicality" as opposed to the current abstractness of it.

> And just warning - all these changes will appear in stable version in a few months, thus please don't expect anything too fast :) Maybe except fixing errors and balancing :)

Simplify the running a test build process if possible(I don't like downloading third party stuff, or *at least* not manually) and I don't mind that at all :-P

**Comment by thindil** [comment]
But "zooming" map will be pure cosmetic change - ship still will be moving with that same speed, just will be doing more "cells" in this same time ;) Plus give players option to set minimal distance between bases.

Islands - I was more thinking about give option to move around the bases (like in normal roguelikes) plus possibility to attacking/defending them. But I totally agree - map for now is too empty, it need a lot more there.

Downloading - that's problem :) One of design in mind for SteamSky was that it should be completely offline. You can always check this development version which are available every 4 weeks. Testing releases - I will see, this generally is designed for really impatient people and developers :) They can be sometimes even more bugged that you can imagine :D

**Comment by thindil** [comment]
About bug with stalled battles - I'm afraid it will be fixed for now only in development version - I have one idea which change enemy behavior in battles, thus probably that change will be too big for the stable version. About other bugs - they now should be fixed and tomorrow will be available a new stable release. Again, thank you for your feedback and I'm back to implementing in the development version your suggestions :)

**Comment by thindil** [comment]
Ok, then as I wrote earlier, because all this small propositions are added to the game, I'm closing this issue. If someone disagree with it, feel free to reopen it ;) And if something is missing from this small things, feel free to ask why they are not added - I will try to explain.
And for now, back to slowly fix this big issues too :)

**Comment by Asmageddon** [comment]
@thindil Well, it is your game :-P All I can do is hint and nudge you a little.

I just think the biggest issue currently is that currently the profitability of activities is inversely proportional to their rarity and interestingness, and the second biggest is that there's very limited nuance despite the abundance of basic content.

**Comment by thindil** [comment]
Nudging is almost always helpful :)
I'm slowly adding some things to the game, so everything is gaining "a deep" or another, own niche. Trading for gaining money, missions for reputation and combat for experience, etc. Just I think every of these parts are still need a lot of work to be a bit more interesting. I think that focus must be more on made every of these things more influential on the game. But we will see :) You are always welcome to scream on me if in your opinion the game will be going in the wrong direction :)

**Comment by Asmageddon** [comment]
@thindil I've just looked at your changelog, and I don't wanna be meaaaannn but whyyyy are you adding so many items with virtually no unique role? Just so many variants of other items @_@

**Comment by thindil** [comment]
At this moment they pretty often don't have too much differences between them, but with time I plan to add more diversity :) Plus remember, trade is very important in this game (it is not too traditional roguelike). It is same as in real life: 90% of items are useless :] https://en.wikipedia.org/wiki/Sturgeon%27s_law

**Comment by Asmageddon** [comment]
@thindil Yeah but games should follow game design, not reality, as its guiding principle. Especially games about flying ships in 2D worlds made up of tiles :-P

I really don't think the game needs 9000 different skillbook items whose only purpose is to be used for skill practice when you could just as easily have the characters practice crafts, or do a job as assistant to another character. Would probably add more nuance too @_@

And there's a reason why a lot of the best trading games often go as far as, for example, just unite every single domestic item into a generic "Domestic Goods" cargo.

If you ever need some rare items, like for specific quests, or collecting, or whatnot, you could just make a "rare variant" of an item, e.g. have a basic item called "Toy", and a rare variant only found in one place in the world called "Yundlan Gear Chess Toy" that has special value and utility due to its rarity, rather than several essentially-identical specimens who for the most part only clog up the UX and force you to have to navigate the menus to "Sell all" on 25 different types of cargo instead of 1.

**Comment by thindil** [comment]
Not at all, I saw also trading games with a lot of different types of this same thing. Probably Dwarf Fortress comes as first, with it "skin from small deer", "skin from medium deer", etc which is only a variant of "skin" :D This is probably one of this differences on which I'm a very stubborn :D 
As I wrote earlier, you have right, now here are no difference between this books except in crafting/durability. But I plan to add some diversity with time (not too soon I'm afraid). Plus I have some idea how to made the whole trading UI (I mean list of goods) less bloated. Just of course it needs a time. Probably I start to be satisfied with the game around version 10.0 or 15.0 :D

**Comment by Asmageddon** [comment]
@thindil Dwarf Fortress is a fantasy simulator first, game second, and not a trading game for that matter. 

Don't undervalue streamlining of content. You should have multiple separate items when it's the most natural way to accommodate new mechanics or niches, not because it's simply possible to create variants of an item. 
You could easily reduce all crafting materials in the game to ingots of N materials, items like "engine/propeller/weapon/logistics component", and a few more specific items like helium tanks(balloons), furniture(cabins, crafting rooms), etc. 
For training you could just have assisting, and assemble/disassemble a craft for practice. For trading you could have a smaller number of generic items like "food", "beverages", "domestic/luxury goods", etc. (I think around 30 globally with some rarer than others would be more than enough) plus rare variants with special significance. 
For ammo you could have low/medium/high caliber ammo in some variants(AP, incendiary, etc.) and have intermediate calibers just use 2x Low Caliber Ammo instead of 1x Low-Medium Caliber Ammo.
For ship modules, you could have only one per type x size combo(e.g. small/medium/large engine/cargo/cabin), and instead give them sub-modules, some mandatory, e.g. this engine bay has Advanced Petroleum Engine in its engine slot 1, Advanced Brass Structure in its structure slot, and in extra slots, some room decorations, and a fire extinguisher cabinet. Gives people some tweaking and tuning to do while lowering the overwhelming amount of content.

...idk. I'm probably trying to cramp on your own direction for the game x.x 

Many skin item can be - sort of, it's not like it really matters - justified by first the fact that different skin have different material properties for making armor and clothing, and the fact that there's mechanics that allow trying to obtain them specifically for that purpose.

IMO, RimWorld is a better design inspiration than Dwarf Fortress, because it takes DF's gameplay value and executes it with 1% as much content, mechanics, and complexity. Of course it doesn't have the simulational depth, but it has a better pacing controlled by an AI director that strives to make sure the player always has something to do, to investigate, to react to, to prepare for.

**Comment by thindil** [comment]
Dwarf Fortress, but still a game ;) Same as Unreal World for example.

As I wrote, I have some ideas how to solve this burden without removing items, we will see how it will be works. I don't like too much that simplicity in games, I definitely prefer very complex games. But talking even about totally different direction on which the game should go is good. Even if you don't convince myself, maybe I will be able to find solution which will be interesting for us both :) So, no worries, feel free to give any advice which in your opinion is good :) I call this "brainstorm" and it often brings interesting ideas :D 

Existence of RimWorld and Dwarf Fortress is the best example that both direction can have fans :)

And before I forget again - this issue (with too much items) you can solve by self, no need to wait for that grumpy developer as me :) This is why Steam Sky have so big modding system - you can easily create mod which will remove and replace all this unnecessary items. All you need is a text editor. And the best thing - you don't need to edit any the game file, thus even with new version, when you upgrade the game, your mod should still works and don't be overwritten by the game files. Most of the game data (not only items but also ships, modules, factions, roles, even bases types) can be changed by creating proper xml file(s). I know that I never create a game which will be interesting for everyone, thus I added so complex modding system. Only the game mechanic can't be modded, but maybe with time it will be possible too :)

**Comment by Asmageddon** [comment]
Streamlining and complexity are two entirely separate metrics. Of course, having a lot of content will make a game harder to wrap your head around, but it's not complexity, it's just a heavy load of stuff to memorize and account for. It's like having to pick the right screwdriver out of a bag with 10000 screwdrivers, instead of being like actually using it to assemble a washing machine.

I'm repeating myself and this is the last time I'll say it, but IMO you really should have as little content to start with as possible, because then everything will have its own purpose in the game, and it will be faster to iterate and improve on your game. It's easier to overhaul a mechanic or balance when it involves 3 items than when it involves 15.

**Comment by thindil** [comment]
We will see ;) And as I said,I have the plan what to do with it, just it need some time to implement :) Everything is in [Wish list](https://github.com/thindil/steamsky/projects/1) :) Even if this not looks like solution for problem of too much item, it can help with it too. And as I wrote earlier, if everything will still not satisfying, you can always just modify the game to your needs.

**Comment by Asmageddon** [comment]
Hello @thindil! 

This isn't really related to this issue, but I thought I'd ask you how you're faring. Doing okey amidst the pandemic? How's your projects, steamsky among them?

**Comment by thindil** [comment]
Hello @Asmageddon 

Thank you very much for asking :) Yes, I'm very well and I hope you also :) I'm right? :D 
And Steam Sky - slowly going forward, I'm slowly implementing all these changes which should be done. A this moment I'm focused on UI - making it less annoying :) If you are interested, I publish weekly reports on itch.io, for example, here: https://thindil.itch.io/steam-sky/devlog/174256/weekly-development-report-20200829
They are also available in RSS channel, so they should be easy to follow.

Once again, thank you for asking and take care :)

**Comment by Asmageddon** [comment]
@thindil That's one swift reply! Thanks. I'm kinda same as ever, which is... don't suppose it can be called good, but I'm doing okay enough. I'll check your weekly updates, though I am not following games that much overall right now. But perhaps I should check out steamsky again and write some more feedback... on the next update, maybe? :0

**Comment by thindil** [comment]
@Asmageddon Good to read that you are ok. And I hope that there will be only better :) About feedback: probably the best option will be wait for the next big release :) This feedback is still "a bit" actual (this is why it is still pinned). At least with the next big release UI should not be a problem.
