### ISSUE TITLE
Unexpected crash while moving (using numpad)

### ISSUE THREAD

**Issue by almostmist** [thindil/steamsky#5]
Unexpected crash while moving (using number pad) away from starting base after undock.

See error.log output below:

```
2017-11-06 14:38:54
Version: 1.8
raised PROGRAM_ERROR : Items.Inventory_Container.Implementation.TC_Check: attempt to tamper with cursors
Call stack traceback locations:
0x5636fc5d74ba 0x5636fc77d31d 0x5636fc77d713 0x5636fc783f08 0x5636fc765344 0x5636fc67d2c5 0x5636fc71fd95 0x5636fc8365ce 0x5636fc5e499f 0x5636fc5e2058 0x7fed7cf561bf 0x5636fc5e20b8 0xfffffffffffffffe
```

**Comment by thindil** [comment]
Hello again ;)
Ugh, I see my bug report system needs some fixes too :) If this is not problem, could you run in terminal command in bin directory where executable is:

`addr2line -e steamsky 0x5636fc5d74ba 0x5636fc77d31d 0x5636fc77d713 0x5636fc783f08 0x5636fc765344 0x5636fc67d2c5 0x5636fc71fd95 0x5636fc8365ce 0x5636fc5e499f 0x5636fc5e2058 0x7fed7cf561bf 0x5636fc5e20b8 0xfffffffffffffffe`

And write here output? It should show files and lines numbers where problem occurs. You don't need to show full path to files, just file names and lines numbers.

**Comment by almostmist** [comment]
Bad news...no files/lines printed:

`/steamsky/bin$ addr2line -e steamsky 0x5636fc5d74ba 0x5636fc77d31d 0x5636fc77d713 0x5636fc783f08 0x5636fc765344 0x5636fc67d2c5 0x5636fc71fd95 0x5636fc8365ce 0x5636fc5e499f 0x5636fc5e2058 0x7fed7cf561bf 0x5636fc5e20b8 0xfffffffffffffffe
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
`

**Comment by thindil** [comment]
Ok, thank you for help and no problem. Bugs in code are my fault :) At this moment, here is no too much to do. I will upgrade error reporting code a bit, it should prevent that situations again. This problem can be everywhere. I think at this moment we can close this issue. If you find any more information fell free to reopen issue.

**Comment by almostmist** [comment]
New crash today while navigating away from starting base (after undock).

```
2017-11-08 11:42:03
Version: 1.8
raised CONSTRAINT_ERROR : crew.adb:1275 overflow check failed
Call stack traceback locations:
0x556e37d4e0ff 0x556e37d4e4ef 0x556e37d51339 0x556e37d5a66f 0x556e37d5d2e0 0x556e37c6f678 0x556e37d11d55 0x556e37e28523 0x556e37bd695f 0x556e37bd4018 0x7f3d6ffe31bf 0x556e37bd4078 0xfffffffffffffffe
```

**Comment by almostmist** [comment]
Same error.log output for a new crash

1. Ship stationary in space
2. Select crew member "on break" from Crew Info menu
3. Assign "Clean ship" (the C in top right is red, so cleaning is needed)

then crash. When I re-load the saved game, I receive the same crash following the above steps. addr2line is still not producing any useful output.

```
2017-11-08 12:17:22
Version: 1.8
raised CONSTRAINT_ERROR : crew.adb:1275 overflow check failed
Call stack traceback locations:
0x5568c081c0ff 0x5568c081c4ef 0x5568c081f339 0x5568c0961fd7 0x5568c06a49a9 0x5568c06a2018 0x7f2d338e41bf 0x5568c06a2078 0xfffffffffffffffe
```
