### ISSUE TITLE
Unable to replace hull.

### ISSUE THREAD

**Issue by ChrisEdBurt** [thindil/steamsky#53]
I am unable to replace my hull, I can`t go to a larger or a smaller version.
I have Small Advanced Iron Hull installed and the "Install Module" button is greyed out on every hull option, both smaller and larger.

Latest CI build of Dev branch.

No error.log and also no save file as I`m away from my PC.
Will submit the save file if you are unable to reproduce.

**Comment by thindil** [comment]
Ok, this time error.log was not needed :) As always, thank you very much for the report and apology for the problems. Should be now fixed.
