### ISSUE TITLE
Removing turret crashes game.

### ISSUE THREAD

**Issue by ChrisEdBurt** [thindil/steamsky#55]
Removing small bronze turret crashes the game, 
I have tried this 3 times in a row and the crash happens each time.

I have attached error.log and save file for reproduction purposes.

[TurretCrashLogSave.zip](https://github.com/thindil/steamsky/files/4190033/TurretCrashLogSave.zip)

**Comment by ChrisEdBurt** [comment]
Latest CI Dev Build Version.

**Comment by thindil** [comment]
(Un)fortunately, this bug was easy to reproduce, thus should be fixed now :) And of course standard: thank you for the report and I'm sorry for the problem :) If the problem will appear again, feel free to scream on me :)
