### ISSUE TITLE
Keyboard commands is enabled while renaming modules

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#61]
When renaming a module (under "Ship information") it is difficult to type, as letters used as keyboard commands activate those commands.

Would be nice if keyboard commands was disabled while typing.

(There are a work around: Type somewhere else, and then [C]opy [V]aste the text in.)

**Comment by thindil** [comment]
Hello, yes, it will be nice but probably for now it will have to wait for a moment or be done in different way. With the next big update of the game, main focus will be on UI and then "a few" things will be changed.

**Comment by thindil** [comment]
And after play a bit with this, looks like another bug in the library (or, to be more specific, bad design). The only way to fix it, is to replace the whole UI library. It is planned for the next stable release. So, for now I just mark it as unable to fix.
