### ISSUE TITLE
Docked in the open during mission

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#62]
During a mission to destroy a ship my ship ended up being docked in the open.

![Screen shot](https://user-images.githubusercontent.com/62181528/76708722-59efd080-66f9-11ea-8439-8357f398c9f1.jpg)

Nasty bug as the game is saved docked, and it crashes when undocking, so it is not possible to continue.

[error.log](https://github.com/thindil/steamsky/files/4334890/error.log)

**Comment by thindil** [comment]
Hello, yes, just a problem - I can't fix it on 100% if I can't reproduce it :( Error.log in that situation will not help too much. If someone will have more information how to reproduce it, please share it.

**Comment by thindil** [comment]
Ok, as I wrote earlier, this one **should** be fixed but it be required a lot of testing to be sure. Thank you again for the report and I'm sorry for the problem. At this moment, the fastest way to get this fix is to use testing version of the game:
https://github.com/thindil/steamsky/tree/4.0#testing-versions
If bug will be still exists, please reopen this issue or create a new.
