### ISSUE TITLE
Crash when selling medicine to quarantined base

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#63]
As the title say, I guess the base can not afford it.

[error.log](https://github.com/thindil/steamsky/files/4343648/error.log)

**Comment by thindil** [comment]
Hello and yes, no money (or not enough money) in the base. I will try to fix it as soon as possible. Thank you very much for the report.

**Comment by thindil** [comment]
So, this one should be fixed too at this moment. Again, thank you very much for the report. Before official release, you can get this fix by using testing version of the game:
https://github.com/thindil/steamsky/tree/4.0#testing-versions
