### ISSUE TITLE
Possible flaw in the economic system

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#64]
Install a module and then remove it again for to earn over 100 000 Charcollum:

![SteamSky](https://user-images.githubusercontent.com/62181528/76909022-68c9b500-68aa-11ea-9005-a5e1e7f36c96.jpg)

**Comment by thindil** [comment]
Hello, and at least, for me it is not that big problem ;) Every operation takes some time, installing/removing isn't instant, especially for these most expensive modules. And in this time you must pay your crew and docking fees. Of course it is still nice profit but not that bad as it can looks for a first glance. I will close this issue, but if you disagree with me, feel free to discuss it here :)
