### ISSUE TITLE
Something weird with goals

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#65]
I did pick the "Visit 1 Pirates base" as goal.
However visiting a Pirates base did not fulfil the goal.
I thought it perhaps was some other base, so I tried other bases.
And something did happen when I did visit an Undead base.
But what exactly, I do not know, as from then on, choosing "Game statistics" make the game crash.

[error.log](https://github.com/thindil/steamsky/files/4349083/error.log)

**Comment by thindil** [comment]
Hello, ok, I will check it very soon. As usual, thank you for the report

**Comment by thindil** [comment]
Ok, this one looks more like bug in incomplete help :) This goal works only on freshly discovered bases. Thus if you have set this goal you have to visit base for the first time (you may know it, but you can't dock before to it). I will update help with that information to avoid confusion. Anyway, at least for me, everything works as expected, no crash and update in the proper base.

**Comment by Lars-Dahl** [comment]
Yes, I did get the goal completed message later when visiting a Pirates base.
But as I could not access the "Game statistics" I could not confirm if it was that goal.

**Comment by thindil** [comment]
Yes, I was trying to reproduce this crash, but with no luck. It was only once or happens always when you enter the game statistics?

**Comment by Lars-Dahl** [comment]
It do happen always.

**Comment by thindil** [comment]
That's very weird, I still can't reproduce this problem :( If it is possible, could you please add here a savegame file with this bug?

**Comment by Lars-Dahl** [comment]
I managed to reproduce it:

[Corvus_Corax_162.zip](https://github.com/thindil/steamsky/files/4355659/Corvus_Corax_162.zip)

**Comment by thindil** [comment]
For now help was clarified so Visit bases goal should not confuse too much. And this crash looks like it is related to something else. I will try to fix it tomorrow.

**Comment by thindil** [comment]
So, this one is finally fixed too. Thank you very much for your help :)
