### ISSUE TITLE
Shipyard module shuffling

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#66]
[error.log](https://github.com/thindil/steamsky/files/4355762/error.log)

How to reproduce:
Go to a shipyard.
Select a module to install.
Switch to "Remove module".
remove cargo bays until you get the message that it can not be sold as there are items in it.
Switch back to "Install module".
Click the button to install the previous selected module.
... and crash!

**Comment by thindil** [comment]
Ok, I will try this and try to fix it as soon as possible ;) As always, thank you for the report.

**Comment by thindil** [comment]
And this one should be fixed now too. Thank you again, for the report. Again, the fastest way to get this fix for now is to use testing version of the game: https://github.com/thindil/steamsky/tree/4.0#testing-versions

**Comment by Lars-Dahl** [comment]
A variant of this:

Go to the shipyard.
Remove a module.
Click the "Remove module" button once more.

[error.log](https://github.com/thindil/steamsky/files/4365583/error.log)

**Comment by thindil** [comment]
Not really a variant, more like a new bug ;) Ok, I will check it soon.

**Comment by thindil** [comment]
This one should be fixed now too. Again, thank you very much for you help.
