### ISSUE TITLE
Friendly trader

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#67]
I am not sure at what triggers this one, but it seems:

Take a package mission, on the way to the destination meet a friendly trader, select "trade" and then the game sometimes crashes.

[error.log](https://github.com/thindil/steamsky/files/4357392/error.log)

**Comment by thindil** [comment]
Hello and standard :) Thank you very much for the report I will try to look at it as soon as possible.

**Comment by thindil** [comment]
This one also should be fixed, just I'm not sure - I can't reproduce this problem. Thank you for the report. If problem will be still exists, please reopen this issue or create new.
