### ISSUE TITLE
Charcollum to whatever transformation

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#68]
Go to a shipyard.
Just before midnight ensure that you have too few Charcollum to pay your crew members.
Remove a module from the ship, so midnight is crossed before completion.
No Charcollum is then earned, instead the amount of the first item at the cargo list is increased!

**Comment by thindil** [comment]
Hello, thanks for the report. Interesting, added to the list to fix ;)

**Comment by thindil** [comment]
And I think, that this one should be fixed too. Again, thank you very much for the help with it.
