### ISSUE TITLE
Game freezes when trying to enter a shipyard

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#69]
I am not sure what triggers it, but quite often, when clicking the shipyard button the game freezes:

![SteamSky3](https://user-images.githubusercontent.com/62181528/77258483-23770000-6c7b-11ea-99c7-f569ddfad177.jpg)

**Comment by thindil** [comment]
Ok, we will see, just this probably will be need more information. At least, how to reproduce it ;)

**Comment by thindil** [comment]
Again, as I see, it is a problem somewhere in the library used by the game, not in game itself. Thus I cannot fix it :( The only way to fix it is to wait to the next big stable release of the game, maybe this one will be fixed too. Thank you very much for the report.
