### ISSUE TITLE
Small User Interface Suggestions/Problems

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#7]
I tried the 1.8 version. Did not play a lot before that.

1. "Backspace" does not work in text fields (eg names, trade amounts etc)
2. Can't exit main menu with "Esc" like all other menus in the game.
3. There is no option to go one menu back. "Esc" always exits to world map.
4. Some screens use "F1" for help but the main screen uses "H".
5. F1 does not work for me, opens the terminal window's help.
6. Help itself is disorganized and it is hard to find what I want. Also you can use color in the help to indicate actions or buttons so that they will be easily spotted.
7. My crew always hungry, I see ratios go down, but can not give a direct order to eat.
8. If there is enough space on the screen, would prefer some quick info box that will display the time of the accepted mission and a quick status of the crew/ship/supplies. It can also be brought with a button, but I want quick access to digested information.
9. Traveling the map using number buttons is not intuitive. Also no help or hints about this. Only the "5" is in the ship movement help.
10. A lot of the time, missions are impossible to complete in the required time frame, even with "Full Speed".

Let me know If you prefer me to open a separate issue for each of these suggestion.

**Comment by thindil** [comment]
Hello and first, thanks for this suggestions/bug reports :)

About separated issues - yes this will be great, please. Few points I can fix without discussion, others I will ask few questions. When you split it, feel free to close this issue (or I will do, if you want).

**Comment by thindil** [comment]
I will close this issue because all of this suggestions/bug reports was divided in few others and all are closed now.
