### ISSUE TITLE
Crew list - unsorted / sorted

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#70]
Not sure if this is a true bug, or just confusing:

Go to "Crew information".
Sort the crew on "Name" or "order".
Modify "Orders priorities" for a member.
Another member then get selected. (At the position the member was at before the sorting!)

I have not studied in details, but directly modifying "Order" in sorted mode is weird in some way.

**Comment by thindil** [comment]
Hello and here we have a problem. It is a bug, but unfortunately not in the game but in the library which the game uses. Thus I'm sorry but this one I cannot fix. I have plan to replace the library but with the next stable version of the game, so it will take some time (and probably brings more, new bugs ;) )
