### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by 2high2play** [thindil/steamsky#71]
I don't know what i did wrong.

all of the saves on this file has crashed

[saves.zip](https://github.com/thindil/steamsky/files/5634158/saves.zip)

**Comment by thindil** [comment]
Hello, thank you for the report and I'm sorry for problems.

I will try to look at it and of course fix it as soon as possible.

**Comment by thindil** [comment]
Ok, I just checked it and it looks like it crash sometimes during ending delivery missions. I think it should be fixed tomorrow and a new version of the game will be released on this Sunday. At this moment, the only way to avoid this crash is to avoid accepting delivery missions ;)

**Comment by thindil** [comment]
And should be fixed now, the new release will be (as wrote above) tomorrow. Thank you very much for the report and I hope here is the end of the mail spam about this problem :smile:
