### ISSUE TITLE
Crash Upon Opening Skills

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#78]
**Describe the bug**
Selecting the skills tab from character info caused the game to crash. Specifically, I was of the drone faction and selected the captain.
[error.log](https://github.com/thindil/steamsky/files/7245637/error.log)

**Technical Info:**
 - OS: Windows
 - Version: 6.0.9

**Comment by thindil** [comment]
Ouch, that is worse than the earlier bug. :) Again, thank you very much for the report and again, I'm sorry for waiting for solving the problem.
As far I see, it breaks only on Drones. Undead, Poleis or Independent factions work good.
It also should be fixed in next few days.

**Comment by thindil** [comment]
Also, this one should be now fixed. Again, thank you very much for the report. 
At this moment, it is possible to prevent this crash by enabling showing numerical values of skills in the game options. Again, if you meet this problem again, feel free to open this issue or create a new about it.
