### ISSUE TITLE
Crash Upon Approaching Enemy

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#79]
**Describe the bug**
I was approaching another ship in combat (full speed), but as I neared, the game crashed. My faction was undead. While the game crashed, re-entering revealed I had rammed them.

[error.log](https://github.com/thindil/steamsky/files/7253667/error.log)

**Technical Info:**
 - OS: Windows
 - Version: 6.0.9

**Comment by thindil** [comment]
Hello, thank you again for the report, I will try to fix it very soon.
I can confirm that problems always happens when you're playing Undead faction. Again, I missed something. ;)

**Comment by thindil** [comment]
This one should be now fixed too. Also thank you for the report. Unfortunately, I don't have a workaround for this one. The only way for now is to download files from here: https://github.com/thindil/steamsky/actions/runs/1293601394 and use them to replace installed ones. As always, if problems will happen again, please reopen the issue or create a new one.
