### ISSUE TITLE
Cant delete backward with BACKSPACE in text fields

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#8]
![screenshot from 2017-11-18 11-33-13](https://user-images.githubusercontent.com/652603/32978945-ab8725ac-cc54-11e7-9b69-0b79aceba56c.png)

**Comment by thindil** [comment]
This is problem mostly with gnome terminal. By default Backspace key in gnome-terminal sends weird signal. I will try to look at it, but temporary solution (can helps with other ncurses programs too): in menu Edit -> Profile Preferences (or something like that) in last tab change value for Backspace key to Control+H

**Comment by thindil** [comment]
And this should be fixed now too, thank you very much for report.
