### ISSUE TITLE
Crash Upon Transporting Drone Passenger

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#81]
**Describe the bug**
Completing a passenger (drone) transport mission crashed the game.
[error.log](https://github.com/thindil/steamsky/files/7255325/error.log)

**Technical Info:**
 - OS: Windows 10
 - Version: 6.0.9

**Comment by thindil** [comment]
Hello and another “ouch” here. Again, thank you for the report, I will try to fix it as soon as possible.

**Comment by thindil** [comment]
Ok, this one should be fixed now too. It took a bit more time, because I found another problems here too, which should be also fixed.
Thank you again for the report, and as usual, if the problem reappears please reopen this issue or create a new. :)
