### ISSUE TITLE
Crash Upon Exploring Area

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#82]
**Describe the bug**
I completed the first stage of the mission 'Explore Area,' and the game crashed.
[error.log](https://github.com/thindil/steamsky/files/7258424/error.log)

**Technical Info:**
 - OS: Windows 10
 - Version: 6.0.9

**Additional context**
I was playing among the drone faction. I've not tested any other. It results in the same error as releasing the passenger, but it doesn't semi-complete (Passenger completes but the mission remains, allowing for infinite looping of the quest for rewards) the mission step. This also occured within the same savegame (all but my first drone bug had).

**Comment by thindil** [comment]
Hello and thank you for the report again. I need to look closer on it. I just tried with Drones either and not crashed. Probably this passenger is causing problems. Thus, continuation of bug #81.

**Comment by thindil** [comment]
I think this one also fixed, unfortunately, after fixing #81 I can't reproduce it. :) Thank you very much for the report and if the problem appears again, please reopen this issue or create a new one. Or just add comment here. :)
