### ISSUE TITLE
Overschooling Consumes Income, Doesn't Increase Level

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#83]
**Describe the bug**
Attempting to increase a skill beyond maximum via the school system at bases will consume the currency, and not increase the level nor price. At least, that's how it appears. This is assuming the 579 cost indicates a maximized skill.

**Technical Info:**
 - OS: Windows 10
 - Version: 6.0.9

**Comment by thindil** [comment]
Hello, thank you for the report and as usual, I'm sorry for troubles. I will look at it (I hope) very soon.

**Comment by thindil** [comment]
Ah, I think I know what happens. Training in schools don't raise level of skill each time, but gives some experience to that skill. Which can or not increase a skill level. It needs a few training sessions to raise a skill level. ;) I think it is a bug in the game documentation. Anyway, at least I found that training not update the game header with the new time, thus thank you for the report.

 If you disagree with the decision, feel free to write comment here or reopen the issue. 😄
