### ISSUE TITLE
Numpad Keys Dysfunctional

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#84]
**Describe the bug**
Despite the keybindings being set, the ship does not move upon pressing any numpad key. I have confirmed my ship was undocked, and also have endeavored to move both with and without numlock. Only the screen is slightly nudged (and does not further nudge during continued pressing). This issue extends to numpad map movement, as well.

**Technical Info:**
 - OS: Windows 10
 - Version: 6.0.9

**Comment by thindil** [comment]
Hello, thank you for the report. I have just one question: if you use the default keyboard settings, do you have enabled keypad with NumLock key? Unfortunately, the keypad works different when is enabled or disabled. I will try to add to the development version something what allows keys to work the same in both states.

**Comment by thindil** [comment]
I'm blind, I'm sorry, now I understand. Hmm, I will look at it. Then another question, is the setting own keys in the game options working properly or numpad keys there also not work?

**Comment by Abstrusle** [comment]
> 
> 
> I'm blind, I'm sorry, now I understand. Hmm, I will look at it. Then another question, is the setting own keys in the game options working properly or numpad keys there also not work?

Replacing with my own keys indeed functions. How, 'ver, when I rebind to numpad, the original KP_# does not return. It becomes 'Home,' 'Left,' etc. or its corresponding number, if numpad is active.

**Comment by thindil** [comment]
I see, thank you for checking. Fortunately I can reproduce it. I hope I can fix it in this week, so it will be shipped with the new release.
