### ISSUE TITLE
Game Freeze From Drone Faction

### ISSUE THREAD

**Issue by ghost** [thindil/steamsky#86]
**Describe the bug**
Entering as the drone faction (with the following settings, though likely not relevant) causes the game to seize:
![image](https://user-images.githubusercontent.com/40145743/136289987-e778fd49-c8d7-4680-9b30-44f2c461a39e.png)

**Technical Info:**
 - OS: Windows 10
 - Version: 6.6

**Comment by thindil** [comment]
Looks like it happens from time to time, not always. Hmm, that one will be hard to catch. My guess, something is wrong with world generation, especially with placing the bases around the map or the player inside the bases.

**Comment by thindil** [comment]
I agree, very strange. I just tried the same: created a new undead, resigned after one move to get into hall of fame, and then started as drone. Still works normally. Also tested on 6.6, 6.0.10 and 6.7 (the last two are future) versions. Maybe there is any `error.log` in directory where saved games are?

**Comment by Abstrusle** [comment]
> 
> 
> Interesting, the logs stops when loading the game goals list, file `goals.dat`. Maybe something corrupted the file during downloading or decompressing?
> 
> If this is not a problem, could you try download and run that freshly downloaded the game? I wonder what happens.

The issue is not present upon redownloading. It must have been corruption.
