### ISSUE TITLE
Issue #85 Unresolved

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#88]
**Describe the bug**
The menu neither offers a 'close' option, nor can I use other keybinds within it.
![image](https://user-images.githubusercontent.com/40145743/136690151-7f5230d8-e43e-4660-9402-7cfc3687e3c6.png)

**Technical Info:**
 - OS: Windows 10
 - Version: 6.0.10

**Comment by thindil** [comment]
Hello, and problems again here. 😞 
1. The “Close” menu entry, as I wrote [here](https://github.com/thindil/steamsky/issues/85#issuecomment-934755520) was added only to the development version.
2. The lack of shortcuts. Looks like Windows only problem, on Linux everything works as expected. I need to look closer on it. In Tk library, menus work differently on OS, thus maybe adding shortcuts to the open menu is impossible on Windows.

**Comment by Abstrusle** [comment]
> 
> 
> Hello, and problems again here. 😞
> 
>     1. The “Close” menu entry, as I wrote [here](https://github.com/thindil/steamsky/issues/85#issuecomment-934755520) was added only to the development version.
> 
>     2. The lack of shortcuts. Looks like Windows only problem, on Linux everything works as expected. I need to look closer on it. In Tk library, menus work differently on OS, thus maybe adding shortcuts to the open menu is impossible on Windows.

I mean, https://thindil.itch.io/steam-sky/devlog/302517/version-6010-is-here stated the patch occured within this version.

**Comment by thindil** [comment]
Ah, I should be more descriptive in the patch, I'm sorry. The close menu should be only in the development version. But shortcuts **should** work in the stable version either. That's why I need to look at it.

**Comment by thindil** [comment]
Better late than never. 😄 But this one finally fixed too. It took that long because I was redesigning other menus too. One, to keep everything in the same style. Two, because the problem could also appear there too. Thank you for the report and I hope for patience. 😁
