### ISSUE TITLE
Can't exit main menu with "ESC"

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#9]
It is possible to exit other menus with the ESC keyboard button. 

The main menu (one opened with "E") can only be exit with "L".

**Comment by thindil** [comment]
It is just for backward compatibility with old keys bindings :) I will change default keyboard settings (need to replace quit game too, Escape is used here). BTW, you can change most in-game shortcuts in game options, so you can set to keys which you prefer.

**Comment by thindil** [comment]
Okies, this one should be now fixed :) As usual, thank you for help.
