### ISSUE TITLE
Mission Auto-complete Fails to Activate

### ISSUE THREAD

**Issue by ghost** [thindil/steamsky#91]
**Describe the bug**
If the player had simultaneously selected more than one mission (I received two destroy ship missions) in a base, they will not auto-complete upon returning.

**Technical Info:**
 - OS: Windows 10
 - Version: 6.0.10

**Comment by thindil** [comment]
I see, I guess only the first mission auto-finish? I will look at it. It should be easy to fix (I hope 😄).

**Comment by thindil** [comment]
Ok, I just checked and looks like everything works. Probably there is a problem with description. Auto finish doesn't work if in the base is currently double price event or when there is no trader on position. I will add this info to the option description to reduce confusion a bit.
