### ISSUE TITLE
Ability to Type in Reward for Mission

### ISSUE THREAD

**Issue by rmvgaines** [thindil/steamsky#96]
Currently when a mission is selected the reward can be adjusted with a slider. It would be helpful to also be able to enter the number directly into a field. For consistency, it seems like most numeric inputs should provide a numeric field or both a numeric field and a slider. Currently, the presentation of these fields varies between views. This issue can be found in the video I linked in my other issue. The issue is present in the current nightly build.

**Comment by thindil** [comment]
Hello and thank you for the idea.

I like the idea and I agree, there is still a lot of work to do with UI. 😉 I will try to add, at least this, but I will look into other fields too. Just the proposition, as it will require some probably more serious changes in the code, will arrive in the next development version, after 8.0 release.

**Comment by thindil** [comment]
And this one also should be added to the game. Again, thank you very much for the idea. I hope I implemented it in the proper way. 😄 If not, feel free to reopen or comment or create a new issue. You can check how it looks in the nightly versions of the game, or wait until release of version 8.1.

Have nice day.
