### ISSUE TITLE
Crash in 8.0.1

### ISSUE THREAD

**Issue by rmvgaines** [thindil/steamsky#99]
[saves.zip](https://github.com/thindil/steamsky/files/10061882/saves.zip)

The game crashed when continuing on path after a battle.

**Comment by thindil** [comment]
I'm trying to reproduce it with the saved game, but I'm unlucky with it. As far I see, the ship is in the base. In which direction should I move?

If I understand correctly the error message from the log file, there is some problem with some file. Maybe during downloading the game, one of the files was corrupted? If it is not a problem, could you please try the saved game with a new installation of the game? Just delete everything or install the game in a different folder and copy the `saves` folder there.

**Comment by rmvgaines** [comment]
Here is a video clip that shows the crash: https://rmvgaines.com/steamsky-8.0.1-crash-video-clip.zip

If I get a chance, I'll try the save with a fresh installation.

**Comment by thindil** [comment]
Thank you for your help. Unfortunately, this time, the error message isn't too helpful. The save shows that everything was saved correctly: you reached the base, returned the mission, and then was the crash. I was thinking also about auto-save, but it is disabled, if I see correctly. I still wonder what could cause the problem. I will try to look at it. Maybe I will be able to reproduce it. 😉

**Comment by thindil** [comment]
Better late than never. 😁 I think this bug **should** be fixed in the latest development version (9.9) and the fix will be available in stable versions from 10.0 onward. But it needs testing. Generally, the whole code related to saving the game was changed.

Thank you again for the report.
